# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfe4d4e0d21e0acaa34a8c8fb07664fa"
name = "gcp-vertex-demo"
handle = "gcp-vertex-demo"
application_url = "https://shopify-gcp-demo.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "myteststore20230808.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://shopify-gcp-demo.onrender.com/auth/callback",
  "https://shopify-gcp-demo.onrender.com/auth/shopify/callback",
  "https://shopify-gcp-demo.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
